title: My Blog
author: Anu Lama
email: anulama@u.boisestate.edu
description: > # this means to ignore newlines until "baseurl:"
  First jekyll page on github

# social links
#twitter_username: your-twitter-handle
github_username:  anulamatamang

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
